### ISSUE TITLE
Add timeouts/retries features to tasks

### ISSUE THREAD

**Issue by bricerisingalgorand** [algorand/mule#11]
Add fields that will be used by jobs to enforce task level configs of timeouts and # of retries.

Defaults:
```python
# in minutes (or seconds if we decide that's better)
timeout = sys.maxint
retries = 1
```

These will be fields like `dependencies` that are available to be set for all tasks and always have the same behavior

**Comment by onetechnical** [comment]
We may be abandoning this, so low priority.
