### ISSUE TITLE
Collect data for perf tests - 500 accounts vs 10 accounts

### ISSUE THREAD

**Issue by bricerisingalgorand** [algorand/mule#71]
## Summary
We need to collect data for whether reducing the number of accounts in a perf test is a bottle neck a perf tests, and if so how much of an impact it has.

## Scope/Requirements
* Run several tests on each scenario and report back with the collected data

## Urgency/Relative Priority
This needs to be done urgently to help guide the perf10x work

**Comment by egieseke** [comment]
Captured results in datadog here: https://app.datadoghq.com/dashboard/q3j-fgw-drp/cicd-performance-dashboard?from_ts=1613466263291&live=false&to_ts=1613527491637&tpl_var_Index=cicd-master-scenario1-cicd-master-scenario1-v1

Reducing the number of accounts from 500 improves the performance of stateful teal tests,  but does not affect the performance of the other tests cases, as seen in this snap shot:

![image](https://user-images.githubusercontent.com/9044640/108311878-ce41b800-7183-11eb-9d16-2a1eb04d8f06.png)

Round time is not impacted: 
![image](https://user-images.githubusercontent.com/9044640/108312003-fd582980-7183-11eb-99a5-0ed149aec1a5.png)

Block size is increased for stateful teal transactions:

![image](https://user-images.githubusercontent.com/9044640/108312379-a56df280-7184-11eb-8f51-0bcd786130a9.png)

Transactions per block is also improved for the stateful teal tests. 

![image](https://user-images.githubusercontent.com/9044640/108312235-62ac1a80-7184-11eb-8702-8ea3470581b2.png)
